In [1]:
%reload_ext autoreload
%autoreload 2

# 자료구조 맵(map): 케이크 초 끼우기

In [2]:
케이크촛불맵 = {}
케이크촛불맵['주황색 구멍'] = '주황색 촛불'
케이크촛불맵['초록색 구멍'] = '초록색 촛불'
케이크촛불맵['파란색 구멍'] = '파란색 촛불'
케이크촛불맵['분홍색 구멍'] = '분홍색 촛불'
print(케이크촛불맵)

{'주황색 구멍': '주황색 촛불', '초록색 구멍': '초록색 촛불', '파란색 구멍': '파란색 촛불', '분홍색 구멍': '분홍색 촛불'}


In [3]:
print(케이크촛불맵['초록색 구멍'])

초록색 촛불


# 자료구조 맵(map): 교통 표지판 만들기

In [1]:
교통표지판맵 = {
    '도로공사중 종이컵': '도로공사중 투명컵',
    '자전거전용도로 종이컵': '자전거전용도로 투명컵',
    '버스전용차로 종이컵': '버스전용차로 투명컵',
    '횡단보도 종이컵': '횡단보도 투명컵',
    '일시정지 종이컵': '일시정지 투명컵',
}
print(교통표지판맵)

{'도로공사중 종이컵': '도로공사중 투명컵', '자전거전용도로 종이컵': '자전거전용도로 투명컵', '버스전용차로 종이컵': '버스전용차로 투명컵', '횡단보도 종이컵': '횡단보도 투명컵', '일시정지 종이컵': '일시정지 투명컵'}


In [ ]:
print(케이크촛불맵['초록색 구멍'])

# 자료구조 큐(Queue): 터널 만들기

In [9]:
from queue import Queue
자동차터널큐 = Queue()
자동차터널큐.put('노란색버스')
자동차터널큐.put('분홍색승용차')
자동차터널큐.put('민트색스포츠카')
print(자동차터널큐.queue)

deque(['노란색버스', '분홍색승용차', '민트색스포츠카'])


In [10]:
print(자동차터널큐.get())
print(자동차터널큐.queue)

노란색버스
deque(['분홍색승용차', '민트색스포츠카'])


# 자료구조 스택(stack): 손수건 뽑기

In [7]:
손수건스택 = []
손수건스택.append('구급차손수건')
손수건스택.append('승용차손수건')
손수건스택.append('로켓손수건')
손수건스택.append('경찰차손수건')
손수건스택.append('헬리콥터손수건')
print(손수건스택)

['구급차손수건', '승용차손수건', '로켓손수건', '경찰차손수건', '헬리콥터손수건']


In [8]:
print(손수건스택.pop())
print(손수건스택.pop())
print(손수건스택)
print(손수건스택.pop())
print(손수건스택.pop())
print(손수건스택.pop())
print(손수건스택)

헬리콥터손수건
경찰차손수건
['구급차손수건', '승용차손수건', '로켓손수건']
로켓손수건
승용차손수건
구급차손수건
[]


# 자료구조 백(bag) & 맵(map): 색 막대 구분하기

In [3]:
통_막대_맵 = {
    '빨간색 통': [],
    '노란색 통': [],
    '초록색 통': [],
}
통_막대_맵['빨간색 통'].append('빨간색 막대')
통_막대_맵['빨간색 통'].append('빨간색 막대')
통_막대_맵['빨간색 통'].append('빨간색 막대')
통_막대_맵['노란색 통'].append('노란색 막대')
통_막대_맵['노란색 통'].append('노란색 막대')
통_막대_맵['초록색 통'].append('초록색 막대')
print(통_막대_맵)

{'빨간색 통': ['빨간색 막대', '빨간색 막대', '빨간색 막대'], '노란색 통': ['노란색 막대', '노란색 막대'], '초록색 통': ['초록색 막대']}


# 자료구조 집합(set): 동물 먹이 주기

In [ ]:
# 

In [2]:
토끼먹이집합 = { '배추', '클로버', '당근' }
수달먹이집합 = { '물고기', '오이', '당근' }

print(f'합집합: {토끼먹이집합 | 수달먹이집합}')
print(f'교집합: {토끼먹이집합 & 수달먹이집합}')
print(f'차집합 (토끼 - 수달): {토끼먹이집합 - 수달먹이집합}')
print(f'차집합 (수달 - 토끼): {수달먹이집합 - 토끼먹이집합}')

합집합: {'배추', '물고기', '클로버', '당근', '오이'}
교집합: {'당근'}
차집합 (토끼 - 수달): {'배추', '클로버'}
차집합 (수달 - 토끼): {'물고기', '오이'}


# 자료구조 행렬(matrix): 클레이 색깔 섞기

In [11]:
import numpy as np

빨파초검클레이행렬 = np.array([
    [ 1, 2 ],
    [ 3, 4 ]
])

흰색클레이행렬  = np.array([
    [ 10, 10 ],
    [ 10, 10 ]
])

print('빨파초검클레이행렬 + 흰색클레이행렬 =')
print(빨파초검클레이행렬 + 흰색클레이행렬)

빨파초검클레이행렬 + 흰색클레이행렬 =
[[11 12]
 [13 14]]


# 자료구조 행렬(matrix): 도형 퍼즐 맞추기

In [8]:
import numpy as np

합친도형행렬 = np.array([
    [ 2, 4 ],
    [ 6, 8 ]
])

반쪽도형행렬1 = np.array([
    [ 1, 2 ],
    [ 3, 4 ]
])

반쪽도형행렬2 = np.array([
    [ 1, 2 ],
    [ 3, 4 ]
])

print('반쪽도형행렬1 + 반쪽도형행렬2 =')
print(반쪽도형행렬1 + 반쪽도형행렬2)
print('합친도형행렬 - 반쪽도형행렬1 =')
print(합친도형행렬 - 반쪽도형행렬1)

반쪽도형행렬1 + 반쪽도형행렬2 =
[[2 4]
 [6 8]]
합친도형행렬 - 반쪽도형행렬1 =
[[1 2]
 [3 4]]


# 자료구조 백(bag) & 맵(map): 도형 분류하기

In [15]:
모양색깔도형맵 = {
    '동그라미': ['파란색동그라미', '빨간색동그라미', '초록색동그라미'],
    '세모': ['빨간색세모', '파란색세모', '초록색세모'],
    '네모': ['파란색네모', '초록색네모', '빨간색네모'],
    '빨간색': ['빨간색세모', '빨간색동그라미', '빨간색네모'],
    '초록색': ['초록색동그라미', '초록색세모', '초록색네모'],
    '파란색': ['파란색네모', '파란색동그라미', '파란색세모'],
}

모양색깔도형맵['네모'].append('보라색네모')
모양색깔도형맵['초록색'].append('초록색별')

print(모양색깔도형맵)

{'동그라미': ['파란색동그라미', '빨간색동그라미', '초록색동그라미'], '세모': ['빨간색세모', '파란색세모', '초록색세모'], '네모': ['파란색네모', '초록색네모', '빨간색네모', '보라색네모'], '빨간색': ['빨간색세모', '빨간색동그라미', '빨간색네모'], '초록색': ['초록색동그라미', '초록색세모', '초록색네모', '초록색별'], '파란색': ['파란색네모', '파란색동그라미', '파란색세모']}


# 자료구조 리스트(list): 병뚜껑 애벌레 놀이

In [16]:
애벌레리스트 = ['빨간색', '노란색', '흰색', '초록색', '보라색']

print(애벌레리스트[0])
print(애벌레리스트[4])
print(애벌레리스트[-1])

빨간색
보라색
보라색


In [18]:
애벌레리스트 = ['빨간색', '노란색', '흰색', '초록색', '보라색']
print(애벌레리스트[0])
print(애벌레리스트[4])
print(애벌레리스트[-1])

애벌레리스트 = []
애벌레리스트.append('빨간색')
애벌레리스트.append('노란색')
애벌레리스트.append('흰색')
애벌레리스트.append('초록색')
애벌레리스트.append('보라색')
print(애벌레리스트)

빨간색
보라색
보라색
['빨간색', '노란색', '흰색', '초록색', '보라색']


# 자료구조 행렬(matrix): 행과 열 색깔 맞추기 

In [21]:
import numpy as np

행끼리행렬 = np.array([
    ['파란색', '파란색', '파란색', '파란색'],
    ['남색', '남색', '남색', '남색'],
    ['보라색', '보라색', '보라색', '보라색'],
])

열끼리행렬 = np.array([
    ['빨간색', '주황색', '노란색', '초록색'],
    ['빨간색', '주황색', '노란색', '초록색'],
    ['빨간색', '주황색', '노란색', '초록색'],
])

print(행끼리행렬[0, :])
print(열끼리행렬[:, 0])

['파란색' '파란색' '파란색' '파란색']
['빨간색' '빨간색' '빨간색']


# 리스트(list) & 원형 큐(circular queue): 주차 타워 놀이

In [12]:
from queue import Queue

주차타워원형큐 = Queue()
주차타워원형큐.put('경찰차')
주차타워원형큐.put('분홍 승용차')
주차타워원형큐.put('자주 승용차')
주차타워원형큐.put('노랑 버스')
주차타워원형큐.put('스포츠카')
print(list(주차타워원형큐.queue))

주차타워원형큐.put(주차타워원형큐.get())
print(list(주차타워원형큐.queue))

주차타워원형큐.put(주차타워원형큐.get())
print(list(주차타워원형큐.queue))

['경찰차', '분홍 승용차', '자주 승용차', '노랑 버스', '스포츠카']
['분홍 승용차', '자주 승용차', '노랑 버스', '스포츠카', '경찰차']
['자주 승용차', '노랑 버스', '스포츠카', '경찰차', '분홍 승용차']


# 큐(queue) & 스택(stack): 비즈 공예 키트로 팔찌 만들기

In [13]:
from queue import Queue

팔찌큐 = Queue()
팔찌큐.put('자주색 팔찌')
팔찌큐.put('하늘색 팔찌')
팔찌큐.put('연두색 팔찌')
팔찌큐.put('노란색 팔찌')
팔찌큐.put('주황색 팔찌')
팔찌큐.put('분홍색 팔찌')
print(팔찌큐.get())
print(팔찌큐.get())
print(팔찌큐.get())
print(팔찌큐.get())
print(팔찌큐.get())
print(팔찌큐.get())

자주색 팔찌
하늘색 팔찌
연두색 팔찌
노란색 팔찌
주황색 팔찌
분홍색 팔찌


In [14]:
팔찌스택 = []
팔찌스택.append('자주색 팔찌')
팔찌스택.append('하늘색 팔찌')
팔찌스택.append('연두색 팔찌')
팔찌스택.append('노란색 팔찌')
팔찌스택.append('주황색 팔찌')
팔찌스택.append('분홍색 팔찌')
print(팔찌스택.pop())
print(팔찌스택.pop())
print(팔찌스택.pop())
print(팔찌스택.pop())
print(팔찌스택.pop())
print(팔찌스택.pop())

분홍색 팔찌
주황색 팔찌
노란색 팔찌
연두색 팔찌
하늘색 팔찌
자주색 팔찌


# 리스트(list) & 스택(stack): 공구 놀이

# 백(bag): 공 던지기 놀이

In [ ]:
케이크상자 = [
    '빨간색공', '초록색공', '파란색공',
    '분홍색공', '연두색공', '하늘색공',
    '노란색공', '보라색공'
]
케이크상자.append('빨간색공')
케이크상자.append('초록색공')
print(케이크상자)

# 연결 리스트(linked list): 무지개 기차

In [ ]:
from cotylab.data_structure.linked_list import LinkedList
무지개기차연결리스트 = LinkedList([
    '빨간색칸', '주황색칸', '노란색칸', 
    '파란색칸', '남색칸', '보라색칸'
])
print(무지개기차연결리스트)

무지개기차연결리스트.next()  # 주황색칸
무지개기차연결리스트.next()  # 노란색칸
무지개기차연결리스트.insert_node('초록색칸')
무지개기차연결리스트.go_to_head()
print(무지개기차연결리스트)