# 자료구조 맵(map): 케이크 초 끼우기

In [2]:
케이크촛불맵 = {}
케이크촛불맵['주황색 구멍'] = '주황색 촛불'
케이크촛불맵['초록색 구멍'] = '초록색 촛불'
케이크촛불맵['파란색 구멍'] = '파란색 촛불'
케이크촛불맵['분홍색 구멍'] = '분홍색 촛불'
print(케이크촛불맵)

{'주황색 구멍': '주황색 촛불', '초록색 구멍': '초록색 촛불', '파란색 구멍': '파란색 촛불', '분홍색 구멍': '분홍색 촛불'}


In [3]:
print(케이크촛불맵['초록색 구멍'])

초록색 촛불


# 자료구조 맵(map): 교통 표지판 만들기

In [1]:
교통표지판맵 = {
    '도로공사중 종이컵': '도로공사중 투명컵',
    '자전거전용도로 종이컵': '자전거전용도로 투명컵',
    '버스전용차로 종이컵': '버스전용차로 투명컵',
    '횡단보도 종이컵': '횡단보도 투명컵',
    '일시정지 종이컵': '일시정지 투명컵',
}
print(교통표지판맵)

{'도로공사중 종이컵': '도로공사중 투명컵', '자전거전용도로 종이컵': '자전거전용도로 투명컵', '버스전용차로 종이컵': '버스전용차로 투명컵', '횡단보도 종이컵': '횡단보도 투명컵', '일시정지 종이컵': '일시정지 투명컵'}


In [ ]:
print(케이크촛불맵['초록색 구멍'])

# 자료구조 큐(Queue): 터널 만들기

In [9]:
from queue import Queue
자동차터널큐 = Queue()
자동차터널큐.put('노란색버스')
자동차터널큐.put('분홍색승용차')
자동차터널큐.put('민트색스포츠카')
print(자동차터널큐.queue)

deque(['노란색버스', '분홍색승용차', '민트색스포츠카'])


In [10]:
print(자동차터널큐.get())
print(자동차터널큐.queue)

노란색버스
deque(['분홍색승용차', '민트색스포츠카'])


# 자료구조 스택(stack): 손수건 뽑기

In [7]:
손수건스택 = []
손수건스택.append('구급차손수건')
손수건스택.append('승용차손수건')
손수건스택.append('로켓손수건')
손수건스택.append('경찰차손수건')
손수건스택.append('헬리콥터손수건')
print(손수건스택)

['구급차손수건', '승용차손수건', '로켓손수건', '경찰차손수건', '헬리콥터손수건']


In [8]:
print(손수건스택.pop())
print(손수건스택.pop())
print(손수건스택)
print(손수건스택.pop())
print(손수건스택.pop())
print(손수건스택.pop())
print(손수건스택)

헬리콥터손수건
경찰차손수건
['구급차손수건', '승용차손수건', '로켓손수건']
로켓손수건
승용차손수건
구급차손수건
[]


# 자료구조 백(bag) & 맵(map): 색 막대 구분하기

In [3]:
통_막대_맵 = {
    '빨간색 통': [],
    '노란색 통': [],
    '초록색 통': [],
}
통_막대_맵['빨간색 통'].append('빨간색 막대')
통_막대_맵['빨간색 통'].append('빨간색 막대')
통_막대_맵['빨간색 통'].append('빨간색 막대')
통_막대_맵['노란색 통'].append('노란색 막대')
통_막대_맵['노란색 통'].append('노란색 막대')
통_막대_맵['초록색 통'].append('초록색 막대')
print(통_막대_맵)

{'빨간색 통': ['빨간색 막대', '빨간색 막대', '빨간색 막대'], '노란색 통': ['노란색 막대', '노란색 막대'], '초록색 통': ['초록색 막대']}


# 자료구조 집합(set): 동물 먹이 주기

In [ ]:
# 

In [2]:
토끼먹이집합 = { '배추', '클로버', '당근' }
수달먹이집합 = { '물고기', '오이', '당근' }

print(f'합집합: {토끼먹이집합 | 수달먹이집합}')
print(f'교집합: {토끼먹이집합 & 수달먹이집합}')
print(f'차집합 (토끼 - 수달): {토끼먹이집합 - 수달먹이집합}')
print(f'차집합 (수달 - 토끼): {수달먹이집합 - 토끼먹이집합}')

합집합: {'배추', '물고기', '클로버', '당근', '오이'}
교집합: {'당근'}
차집합 (토끼 - 수달): {'배추', '클로버'}
차집합 (수달 - 토끼): {'물고기', '오이'}


# 자료구조 행렬(matrix): 클레이 색깔 섞기

In [11]:
import numpy as np

빨파초검클레이행렬 = np.array([
    [ 1, 2 ],
    [ 3, 4 ]
])

흰색클레이행렬  = np.array([
    [ 10, 10 ],
    [ 10, 10 ]
])

print('빨파초검클레이행렬 + 흰색클레이행렬 =')
print(빨파초검클레이행렬 + 흰색클레이행렬)

빨파초검클레이행렬 + 흰색클레이행렬 =
[[11 12]
 [13 14]]


# 자료구조 행렬(matrix): 도형 퍼즐 맞추기

In [8]:
import numpy as np

합친도형행렬 = np.array([
    [ 2, 4 ],
    [ 6, 8 ]
])

반쪽도형행렬1 = np.array([
    [ 1, 2 ],
    [ 3, 4 ]
])

반쪽도형행렬2 = np.array([
    [ 1, 2 ],
    [ 3, 4 ]
])

print('반쪽도형행렬1 + 반쪽도형행렬2 =')
print(반쪽도형행렬1 + 반쪽도형행렬2)
print('합친도형행렬 - 반쪽도형행렬1 =')
print(합친도형행렬 - 반쪽도형행렬1)

반쪽도형행렬1 + 반쪽도형행렬2 =
[[2 4]
 [6 8]]
합친도형행렬 - 반쪽도형행렬1 =
[[1 2]
 [3 4]]


# 자료구조 백(bag) & 맵(map): 도형 분류하기

In [15]:
모양색깔도형맵 = {
    '동그라미': ['파란색동그라미', '빨간색동그라미', '초록색동그라미'],
    '세모': ['빨간색세모', '파란색세모', '초록색세모'],
    '네모': ['파란색네모', '초록색네모', '빨간색네모'],
    '빨간색': ['빨간색세모', '빨간색동그라미', '빨간색네모'],
    '초록색': ['초록색동그라미', '초록색세모', '초록색네모'],
    '파란색': ['파란색네모', '파란색동그라미', '파란색세모'],
}

모양색깔도형맵['네모'].append('보라색네모')
모양색깔도형맵['초록색'].append('초록색별')

print(모양색깔도형맵)

{'동그라미': ['파란색동그라미', '빨간색동그라미', '초록색동그라미'], '세모': ['빨간색세모', '파란색세모', '초록색세모'], '네모': ['파란색네모', '초록색네모', '빨간색네모', '보라색네모'], '빨간색': ['빨간색세모', '빨간색동그라미', '빨간색네모'], '초록색': ['초록색동그라미', '초록색세모', '초록색네모', '초록색별'], '파란색': ['파란색네모', '파란색동그라미', '파란색세모']}


# 자료구조 리스트(list): 병뚜껑 애벌레 놀이

In [16]:
애벌레리스트 = ['빨간색', '노란색', '흰색', '초록색', '보라색']

print(애벌레리스트[0])
print(애벌레리스트[4])
print(애벌레리스트[-1])

빨간색
보라색
보라색


In [18]:
애벌레리스트 = ['빨간색', '노란색', '흰색', '초록색', '보라색']
print(애벌레리스트[0])
print(애벌레리스트[4])
print(애벌레리스트[-1])

애벌레리스트 = []
애벌레리스트.append('빨간색')
애벌레리스트.append('노란색')
애벌레리스트.append('흰색')
애벌레리스트.append('초록색')
애벌레리스트.append('보라색')
print(애벌레리스트)

빨간색
보라색
보라색
['빨간색', '노란색', '흰색', '초록색', '보라색']


# 자료구조 행렬(matrix): 행과 열 색깔 맞추기 

In [21]:
import numpy as np

행끼리행렬 = np.array([
    ['파란색', '파란색', '파란색', '파란색'],
    ['남색', '남색', '남색', '남색'],
    ['보라색', '보라색', '보라색', '보라색'],
])

열끼리행렬 = np.array([
    ['빨간색', '주황색', '노란색', '초록색'],
    ['빨간색', '주황색', '노란색', '초록색'],
    ['빨간색', '주황색', '노란색', '초록색'],
])

print(행끼리행렬[0, :])
print(열끼리행렬[:, 0])

['파란색' '파란색' '파란색' '파란색']
['빨간색' '빨간색' '빨간색']
